package com.ps.eca.user.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.ps.eca.user.model.enums.UserRole;
import com.ps.eca.user.util.converter.UserRoleConverter;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "User")
public class User {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @DynamoDBAttribute(attributeName = "mobile")
    private String mobile;

    @DynamoDBAttribute(attributeName = "role")
    @DynamoDBTypeConverted(converter = UserRoleConverter.class)
    private UserRole role;
}