package com.ps.eca.apartment.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.List;

@Data
@DynamoDBTable(tableName = "Apartment")
public class Apartment {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "location")
    private String location;

    @DynamoDBAttribute(attributeName = "type")
    private String type;

    @DynamoDBAttribute(attributeName = "apartmentNumber")
    private String apartmentNumber;

    @DynamoDBAttribute(attributeName = "floor")
    private String floor;

    @DynamoDBAttribute(attributeName = "ownerUserId")
    private String ownerUserId;

    @DynamoDBAttribute(attributeName = "amenities")
    private List<String> amenities;

    @DynamoDBAttribute(attributeName = "age")
    private int age;

    @DynamoDBAttribute(attributeName = "bedrooms")
    private int bedrooms;

    @DynamoDBAttribute(attributeName = "bathrooms")
    private int bathrooms;

    @DynamoDBAttribute(attributeName = "price")
    private double price;

    @DynamoDBAttribute(attributeName = "forRent")
    private boolean forRent;

    @DynamoDBAttribute(attributeName = "available")
    private boolean available;

    @DynamoDBAttribute(attributeName = "sizeInSquareFeet")
    private double sizeInSquareFeet;
}